name: Deploy Smart TV to Production

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, production-smart-tv]
    environment: PRODUCTION

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: git pull origin main
    - run: yarn install
    - run: yarn build-production
    - run: pm2 reload all --update-env
